// ChoViva Producer Catalogue — public directory data
// Redacted from the internal Q3 2026 Partner Catalogue: no contact details,
// private-label matrices, delivery-region tables, or addresses are included.
// Source figures (stats block) are pre-cleared Planet A Foods claims — do not alter.

const CATEGORIES = [
  { id: "confectionery", label: "Confectionery" },
  { id: "biscuits-bakery", label: "Biscuits & Bakery" },
  { id: "bake-off", label: "Bake Off" },
  { id: "ice-cream", label: "Ice Cream" },
  { id: "other", label: "Other" },
];

const PRODUCERS = [
  // ---------------- Confectionery ----------------
  {
    name: "Treets GmbH | Piasten GmbH",
    logo: "images/logos/logo-treets-gmbh-piasten-gmbh.png",
    category: "confectionery",
    focus: "Dragées · Bite-sized snacks",
    website: "https://www.treets.eu",
    products: [
      { name: "Treets Crunchy Corn", sizes: "210g / 120g / 85g", vegan: true, img: "images/img_c73ba251.png" },
      { name: "Treets Peanuts", sizes: "200g / 185g / 150g / 100g / 85g / 45g", vegan: true, img: "images/img_9f1898f7.png" },
      { name: "Treets Crispy", sizes: "175g / 120g", vegan: true, img: "images/img_bfd23188.png" },
      { name: "Treets Salted Peanuts", sizes: "200g / 185g / 150g", vegan: true, img: "images/img_a00f5ef5.png" },
      { name: "Treets Pretzel Bites", sizes: "175g", vegan: true, img: "images/img_20066af3.png" },
      { name: "Treets Buttons", sizes: "165g", vegan: true, img: "images/img_e9cc66f4.png" },
    ],
  },
  {
    name: "WAWI-Euro GmbH",
    logo: "images/logos/logo-wawi-euro-gmbh.png",
    category: "confectionery",
    focus: "Pralines · Puffed rice chocolates",
    website: "https://www.wawi-group.de",
    products: [
      { name: "Peanut Butter Cups", sizes: "126g / 110g", vegan: false, img: "images/img_2ef90a41.png" },
      { name: "Banana Split Cups", sizes: "120g", vegan: false, img: "images/img_720de27c.png" },
      { name: "White Butter Cups", sizes: "126g / 120g", vegan: false, img: "images/img_fa6af95d.png" },
      { name: "Alwins Salted Caramel", sizes: "100g", vegan: false, img: "images/img_91bda5ee.png" },
      { name: "Duckies Marshmallow", sizes: "100g", vegan: false, img: "images/img_9bbf5b3b.png" },
      { name: "Mini Wichtel Nougat", sizes: "110g", vegan: false, img: "images/img_b56a2f47.png" },
      { name: "Männlis Caramel", sizes: "100g", vegan: false, img: "images/img_4a88dc8d.png" },
      { name: "Männlis Gingerbread", sizes: "100g", vegan: false, img: "images/img_08832a61.png" },
      { name: "Peanut Butter Eggs", sizes: "90g", vegan: false, img: "images/img_4f2b4e8c.png" },
      { name: "Salted Caramel Eggs", sizes: "90g", vegan: false, img: "images/img_304f7027.png" },
      { name: "Puffed Rice & Cornflakes Bar", sizes: "100g", vegan: false, img: "images/img_6568103c.png" },
      { name: "Puffed Rice Bar", sizes: "100g", vegan: false, img: "images/img_42e186ec.png" },
      { name: "Puffed Spelt Bar", sizes: "45g", vegan: true, img: "images/img_af07059c.png" },
      { name: "Creamy Milk Gonk", sizes: "30g", vegan: false, img: "images/img_6677dd9d.png" },
      { name: "Creamy Crisp Gonk", sizes: "30g", vegan: false, img: "images/img_6c59f459.png" },
      { name: "Wicked Cat Crème Filling", sizes: "30g", vegan: false, img: "images/img_861181f5.png" },
      { name: "Wicked Cat Salted Caramel Filling", sizes: "30g", vegan: false, img: "images/img_c596eee6.png" },
      { name: "Grinch Crème Filling", sizes: "30g", vegan: false, img: "images/img_f85b0269.png" },
    ],
  },
  {
    name: "Hans Riegelein & Sohn GmbH & Co. KG",
    logo: "images/logos/logo-hans-riegelein-sohn-gmbh-co-.png",
    category: "confectionery",
    focus: "Puffed rice snacks · Seasonal products",
    website: "https://riegelein.de",
    products: [
      { name: "Sun Rice Original 2.0 Happen", sizes: "250g / 150g / 45g", vegan: false, img: "images/img_a65d13f4.png" },
      { name: "Sun Rice Crunchy White Milk & Flakes Happen", sizes: "250g", vegan: false, img: "images/img_5c37d0ca.png" },
      { name: "Sun Rice Crunchy Milk & Flakes Happen", sizes: "250g", vegan: false, img: "images/img_cc969010.png" },
      { name: "Puffreis Crunchy Nut Happen", sizes: "250g", vegan: false, img: "images/img_55b90f75.png" },
      { name: "Sun Rice Crunchy Milk & Cereal Bar", sizes: "40g", vegan: false, img: "images/img_1da80441.png" },
      { name: "Sun Rice Original 2.0 Bar", sizes: "150g", vegan: false, img: "images/img_21bb6a29.png" },
      { name: "Peanut Snack", sizes: "400g / 300g", vegan: false, img: "images/img_3fb1b567.png" },
      { name: "Seasonal Hollow Figure", sizes: "200g", vegan: false, img: "images/img_62457998.png" },
    ],
  },
  {
    name: "Rau Chocolates & Cereals",
    logo: "images/logos/logo-rau-chocolates-cereals.png",
    category: "confectionery",
    focus: "Cereal products · Coated popcorn",
    website: "https://www.rau-chocolate-cereals.de",
    products: [
      { name: "Knusper Flakes Coconut", sizes: "125g", vegan: false, img: "images/img_b48fb70f.png" },
      { name: "Knusper Flakes Strawberry", sizes: "125g", vegan: false, img: "images/img_3f66a7fb.png" },
      { name: "Butter Cookie Popcorn Mix", sizes: "180g", vegan: false, img: "images/img_fd303679.png" },
      { name: "Strawberry Cheesecake Popcorn Mix", sizes: "180g", vegan: false, img: "images/img_b2667477.png" },
      { name: "Salty Prezel-Mix Popcorn", sizes: "180g", vegan: false, img: "images/img_salz_7aa17af8.png" },
      { name: "Marshmallow Popcorn", sizes: "180g", vegan: false, img: "images/img_marsh_101d6898.png" },
      { name: "White Coconut Popcorn", sizes: "180g", vegan: false, img: "images/img_38cc7719.png" },
      { name: "Date Confection", sizes: "200g", vegan: false, img: "images/img_9105c478.png" },
      { name: "Easter Bag", sizes: "130g", vegan: false, img: "images/img_b7ea1e0e.png" },
    ],
  },
  {
    name: "Chocolaterie Abtey S.A.",
    logo: "images/logos/logo-chocolaterie-abtey-s-a.png",
    category: "confectionery",
    focus: "Chocolate tablets · Pralines",
    website: "https://abtey.fr",
    products: [
      { name: "Abtey Tablet Milk", sizes: "100g", vegan: false, img: "images/img_49635b0d.png" },
      { name: "Abtey Tablet Hazelnut", sizes: "100g", vegan: false, img: "images/img_67c68cc3.png" },
      { name: "Abtey Tablet Feuilletine", sizes: "100g", vegan: false, img: "images/img_7ded5300.png" },
      { name: "Abtey Pralins Feuilletine", sizes: "162g", vegan: false, img: "images/img_43aec0f6.png" },
      { name: "Abtey Pralins Hazelnut", sizes: "162g", vegan: false, img: "images/img_2773d451.png" },
      { name: "Abtey Hollow Figure", sizes: "120g / 130g", vegan: false, img: "images/img_a049b875.png" },
      { name: "Abtey Jungle Eggs", sizes: "200g", vegan: false, img: "images/img_27a7ab3e.png" },
      { name: "Abtey Mini Bottles", sizes: "200g", vegan: false, img: "images/img_351ed1b7.png" },
      { name: "Abtey Mini Umbrellas", sizes: "200g", vegan: false, img: "images/img_745d418c.png" },
      { name: "Abtey Mini Unicorns", sizes: "200g", vegan: false, img: "images/img_166309d5.png" },
      { name: "Abtey Mini Bottles I / II / III", sizes: "81g", vegan: false, img: "images/img_6ba55ed9.png" },
      { name: "Abtey Mini Bottles Mojito & Gin", sizes: "81g", vegan: false, img: "images/img_7fa4c1c8.png" },
    ],
  },
  {
    name: "Hands Off B.V.",
    logo: "images/logos/logo-hands-off-b-v.png",
    category: "confectionery",
    focus: "Filled bars · Pralines",
    website: null,
    products: [
      { name: "Milano Hazelnut Soft Core", sizes: "100g", vegan: true, img: "images/img_66c4b1db.png" },
      { name: "New York Peanut Butter Soft Core", sizes: "100g", vegan: true, img: "images/img_0a0bdfe0.png" },
      { name: "Amsterdam Speculoos Soft Core", sizes: "100g", vegan: true, img: "images/img_c5cd4fcd.png" },
    ],
  },
  {
    name: "Nestlé S.A.",
    logo: "images/logos/logo-nestl-s-a.png",
    category: "confectionery",
    focus: "Bite-size snacks · Bars",
    website: null,
    products: [
      { name: "Nestlé Choco Crossies Snack Vibes Classic", sizes: "100g", vegan: false, img: "images/img_feed2131.png" },
      { name: "Nestlé Choco Crossies Salted Popcorn Caramel", sizes: "100g", vegan: false, img: "images/img_a8fd4bdb.png" },
      { name: "Nestlé Choco Crossies Snack Vibes Hazelnut", sizes: "100g", vegan: false, img: "images/img_ac2a242d.png" },
    ],
  },
  {
    name: "Mars Inc.",
    logo: "images/logos/logo-mars-inc.png",
    category: "confectionery",
    focus: "Bite sized snacks · Bars",
    website: null,
    products: [
      { name: "Mars Balisto Trail Mix", sizes: "140g", vegan: false, img: "images/img_0465e37d.png" },
    ],
  },
  {
    name: "JOKOLADE GmbH",
    logo: "images/logos/logo-jokolade.png",
    category: "confectionery",
    focus: "Bite sized snacks · Tablets",
    website: null,
    products: [
      { name: "Filled Ice Cream Cones", sizes: "100g", vegan: true, img: "images/img_df9be4b6.png" },
      { name: "Filled Ice Cream Cones w. Hazelnut", sizes: "100g", vegan: true, img: "images/img_5bffc287.png" },
      { name: "Jokolade Tablet with Inclusions", sizes: "140g", vegan: true, img: "images/img_c0968e65.png" },
      { name: "Jokolade Bar with Inclusions", sizes: "40g", vegan: true, img: "images/img_9206ab72.png" },
    ],
  },
  {
    name: "Bitecone SAS",
    logo: "images/logos/logo-bitecone-sas.png",
    category: "confectionery",
    focus: "Bite sized snacks · Wafers",
    website: null,
    products: [
      { name: "Filled Ice Cream Cones", sizes: "100g", vegan: true, img: "images/img_72b30c95.png" },
    ],
  },
  {
    name: "Libeert NV",
    logo: "images/logos/logo-libeert-nv.png",
    category: "confectionery",
    focus: "Bars · Pralines",
    website: null,
    products: [
      { name: "Tablet with Inclusions", sizes: "140g", vegan: true, img: "images/img_b00d5be6.png" },
      { name: "Bar with Inclusions", sizes: "40g", vegan: true, img: "images/img_1fe2b9e0.png" },
    ],
  },
  {
    name: "Ludwig Schokolade GmbH & Co. KG",
    logo: "images/logos/logo-ludwig-schokolade-gmbh-co-kg.png",
    category: "confectionery",
    focus: "Tablets · Pralines",
    website: null,
    products: [
      { name: "Cookie & Hazelnut Tablet", sizes: "80g", vegan: false, img: "images/img_eec00ce1.png" },
      { name: "Salted Pretzel Tablet", sizes: "80g", vegan: false, img: "images/img_abc0484e.png" },
      { name: "Salted Butter Cookie Tablet", sizes: "80g", vegan: false, img: "images/img_09ab1c03.png" },
      { name: "Small Bites", sizes: "100g", vegan: false, img: "images/img_3064f9e3.png" },
    ],
  },

  // ---------------- Biscuits & Bakery ----------------
  {
    name: "Biscuit International",
    logo: "images/logos/logo-biscuit-international.png",
    category: "biscuits-bakery",
    focus: "Biscuits · Rice cakes",
    website: "https://biscuitinternational.com",
    products: [
      { name: "Wafer Sheets", sizes: "100g", vegan: false, img: "images/img_a6db14a8.png" },
      { name: "Salty ChoViva Cookie", sizes: "100g", vegan: false, img: "images/img_41de740d.png" },
      { name: "Squared Rice Cake", sizes: "55g", vegan: false, img: "images/img_9765103e.png" },
      { name: "Squared Corn Cakes", sizes: "55g", vegan: false, img: "images/img_de6965c1.png" },
    ],
  },
  {
    name: "Borggreve Zwieback- und Keksfabrik KG",
    logo: "images/logos/logo-borggreve-zwieback-und-keksf.png",
    category: "biscuits-bakery",
    focus: "Chocolate biscuits · Seasonal items",
    website: "https://borggreve.de",
    products: [
      { name: "Süße Tatzen Biscuits", sizes: "250g", vegan: false, img: "images/img_e07db951.png" },
      { name: "Spritz Biscuits", sizes: "250g", vegan: false, img: "images/img_771eaef4.png" },
      { name: "Almond Spritz Biscuits", sizes: "300g", vegan: false, img: "images/img_03ebe749.png" },
      { name: "Coconut Spritz Biscuits", sizes: "300g", vegan: false, img: "images/img_6da005c3.png" },
      { name: "Vanille Spritz Biscuits", sizes: "300g", vegan: false, img: "images/img_3954bde3.png" },
    ],
  },
  {
    name: "Griesson - De Beukelaer GmbH & Co. KG",
    logo: "images/logos/logo-griesson-de-beukelaer-gmbh-c.png",
    category: "biscuits-bakery",
    focus: "Biscuits · Wafers",
    website: null,
    products: [
      { name: "De Beukelaer Cereola Der Klassiker", sizes: "150g", vegan: true, img: "images/img_8cd1ad17.png" },
      { name: "De Beukelaer Cereola Cookies", sizes: "150g", vegan: true, img: "images/img_6ffdb6b2.png" },
      { name: "De Beukelaer Cereola Oaties", sizes: "130g", vegan: true, img: "images/img_5967f757.png" },
      { name: "De Beukelaer Eis-Waffeln", sizes: "50g", vegan: true, img: "images/img_e1f92434.png" },
    ],
  },
  {
    name: "Henry Lambertz GmbH & Co. KG",
    logo: "images/logos/logo-henry-lambertz-gmbh-co-kg.png",
    category: "biscuits-bakery",
    focus: "Biscuits · Pralines",
    website: "https://lambertz.de",
    products: [
      { name: "Lambertz Peanut Clusters", sizes: "200g", vegan: true, img: "images/img_800a06ab.png" },
      { name: "Lambertz Flake Clusters", sizes: "200g", vegan: true, img: "images/img_1b035d33.png" },
      { name: "Almond Horns", sizes: "175g", vegan: false, img: "images/img_8fd95e7a.png" },
      { name: "Nut Squares", sizes: "200g", vegan: false, img: "images/img_4277f235.png" },
      { name: "Peanut Slices", sizes: "175g", vegan: false, img: "images/img_3134fb92.png" },
      { name: "Nut Slices", sizes: "175g", vegan: false, img: "images/img_5f3ee43b.png" },
    ],
  },
  {
    name: "S. Spitz GmbH",
    logo: "images/logos/logo-s-spitz-gmbh.png",
    category: "biscuits-bakery",
    focus: "Wafers · Bite size snacks",
    website: null,
    products: [
      { name: "Hazelnut Rolls", sizes: "400g", vegan: false, img: "images/img_5f509db9.png" },
      { name: "Mignon Wafers", sizes: "400g", vegan: true, img: "images/img_mignon_3a99182a.png" },
      { name: "Neapolitan Wafers", sizes: "65g", vegan: false, img: "images/img_322e63b3.png" },
    ],
  },
  {
    name: "Dr. Quendt GmbH & Co.KG",
    logo: "images/logos/logo-dr-quendt.png",
    category: "biscuits-bakery",
    focus: "Baking mixes · Baking ingredients",
    website: null,
    products: [
      { name: "Hafer Q's", sizes: "100g", vegan: true, img: "images/img_49f98c14.png" },
    ],
  },
  {
    name: "Conrad Schulte GmbH & Co. KG",
    logo: "images/logos/logo-conrad-schulte-gmbh-co-kg.png",
    category: "biscuits-bakery",
    focus: "Seasonal products · Biscuits",
    website: "https://schulte-feingebaeck.de",
    products: [
      { name: "Schulte Dominosteine Dark", sizes: "125g", vegan: false, img: "images/img_93d7f2d1.png" },
      { name: "Schulte Dominosteine Milk", sizes: "125g / 2200g", vegan: false, img: "images/img_a8101569.png" },
      { name: "Schulte Dominosteine White", sizes: "125g", vegan: false, img: "images/img_b7c3dd1c.png" },
      { name: "Premium Dominosteine Egg Liquor", sizes: "175g", vegan: false, img: "images/img_a83b12e1.png" },
      { name: "Premium Dominosteine Winterpunch", sizes: "175g", vegan: false, img: "images/img_7f254832.png" },
      { name: "Premium Dominosteine Hazelnut", sizes: "175g", vegan: false, img: "images/img_6b4e16fc.png" },
      { name: "Schulte Kipferl", sizes: "175g", vegan: false, img: "images/img_3b809247.png" },
      { name: "Schulte Mini Spekulatius", sizes: "200g / 2200g", vegan: false, img: "images/img_51dfcb3e.png" },
      { name: "Mini Nut Corners", sizes: "175g", vegan: false, img: "images/img_46a2c9c3.png" },
      { name: "Spiced Slices", sizes: "175g", vegan: false, img: "images/img_ef285294.png" },
      { name: "Hearts Stars & Pretzels", sizes: "2500g", vegan: false, img: "images/img_6b6c304e.png" },
    ],
  },
  {
    name: "Coppenrath Feingebäck GmbH",
    logo: "images/logos/logo-coppenrath-feingeb-ck-gmbh.png",
    category: "biscuits-bakery",
    focus: "Biscuits · Seasonal products",
    website: "https://coppenrath-feingebaeck.de",
    products: [
      { name: "Coppenrath ChOATlate Coooky Hafer", sizes: "175g", vegan: false, img: "images/img_361f6e58.png" },
      { name: "Coppenrath ChOATlate Coooky Vanille", sizes: "175g", vegan: false, img: "images/img_d1b09ec5.png" },
      { name: "Coppenrath ChOATlate Coooky Karamell", sizes: "175g", vegan: false, img: "images/img_6db86e71.png" },
      { name: "Confiserie Taler Blau", sizes: "150g", vegan: false, img: "images/img_dd5468f0.png" },
      { name: "Confiserie Taler Rot", sizes: "150g", vegan: false, img: "images/img_49125d70.png" },
    ],
  },
  {
    name: "Hans Freitag GmbH & Co. KG",
    logo: "images/logos/logo-hans-freitag-gmbh-co-kg.png",
    category: "biscuits-bakery",
    focus: "Bite sized snacks · Biscuits",
    website: null,
    products: [
      { name: "Private Label Waffle Bites", sizes: "125g", vegan: false, img: "images/img_fb25ed2d.png" },
    ],
  },
  {
    name: "Spreewaffel Berlin-Pankow GmbH",
    logo: "images/logos/logo-spreewaffel-berlin-pankow-gm.png",
    category: "biscuits-bakery",
    focus: "Wafers · Biscuits",
    website: null,
    products: [
      { name: "Knusper Waffeln", sizes: "100g", vegan: true, img: "images/img_79eda4a8.png" },
    ],
  },
  {
    name: "Dan Cake A/S",
    logo: "images/logos/logo-dan-cake-a-s.png",
    category: "biscuits-bakery",
    focus: "Bakery · Cakes",
    website: null,
    products: [
      { name: "Muffins Schoko & Stracciatella", sizes: "360g", vegan: false, img: "images/img_9a34f755.png" },
    ],
  },
  {
    name: "SanoRice Holding B.V.",
    logo: "images/logos/logo-sanorice-holding-b-v.png",
    category: "biscuits-bakery",
    focus: "Rice cakes",
    website: null,
    products: [
      { name: "Rice Cake", sizes: "50g", vegan: false, img: "images/img_2e668254.png" },
    ],
  },

  // ---------------- Bake Off ----------------
  {
    name: "BAKER & BAKER Germany GmbH",
    logo: "images/logos/logo-baker-baker-germany-gmbh.png",
    category: "bake-off",
    focus: "Bakery · Cakes",
    website: null,
    products: [
      { name: "Cinnamon Roll", sizes: "115g", vegan: true, img: "images/img_3aba5704.png" },
      { name: "Donut Dark", sizes: "56g", vegan: true, img: "images/img_5220a95e.png" },
      { name: "Muffin", sizes: "110g", vegan: false, img: "images/img_e37b4698.png" },
      { name: "Donut White", sizes: "56g", vegan: false, img: "images/img_cbf5b176.png" },
    ],
  },

  // ---------------- Ice Cream ----------------
  {
    name: "Eisbär Eis GmbH",
    logo: "images/logos/logo-eisb-r-eis-gmbh.png",
    category: "ice-cream",
    focus: "Ice cream",
    website: null,
    products: [
      { name: "Salted Caramel mit Hazelnut Crunch", sizes: "250g", vegan: false, img: "images/img_ccea8160.png" },
      { name: "Private Label Classic Stieleis", sizes: "480g", vegan: false, img: "images/img_33319437.png" },
      { name: "Private Label Mandel Stieleis", sizes: "480g", vegan: false, img: "images/img_690ab4c7.png" },
    ],
  },

  // ---------------- Other ----------------
  {
    name: "KATHI Rainer Thiele GmbH",
    logo: "images/logos/logo-kathi-rainer-thiele-gmbh.png",
    category: "other",
    focus: "Baking mixes · Baking ingredients",
    website: null,
    products: [
      { name: "Mini Banana Cupcake mix", sizes: "380g", vegan: false, img: "images/img_219c9550.png" },
    ],
  },
  {
    name: "H. & J. Brüggen KG",
    logo: "images/logos/logo-h-j-br-ggen-kg.png",
    category: "other",
    focus: "Cereals · Mueslis",
    website: null,
    products: [
      { name: "Crunchy Oat Hazelnut Muesli", sizes: "500g", vegan: true, img: "images/img_dc1533ad.png" },
      { name: "Crunchy Oat Berry Muesli", sizes: "500g", vegan: true, img: "images/img_020f05eb.png" },
      { name: "Crunchy ChoViva Oat Muesli", sizes: "500g", vegan: true, img: "images/img_e469495e.png" },
    ],
  },
];
